services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - .node-red/:/data
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9002"
    volumes:
      - .mqtt/etc:/etc/mosquitto
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf